#!/bin/sh

COMMIT_MESSAGE_FILE=$1
COMMIT_MESSAGE=$(cat "$COMMIT_MESSAGE_FILE")

echo "----------------------------------"
echo "📝 커밋 메시지 규칙을 검사합니다..."
echo "----------------------------------"
echo "💬 커밋 메시지: \"$COMMIT_MESSAGE\""
echo "----------------------------------"

# commitlint 실행 및 결과 확인
if npx commitlint --edit "$COMMIT_MESSAGE_FILE"; then
  echo "✅ 커밋 메시지가 규칙에 맞습니다! 커밋을 진행합니다."
  echo "----------------------------------"
  exit 0
else
  echo "🚫 커밋 메시지가 규칙에 맞지 않습니다! 규칙에 맞게 수정하세요."
  echo "----------------------------------"
  exit 1
fi
